# @generated: Generated with gen_build_npm.py

package(default_visibility = ['//visibility:public'])

load('@org_dropbox_rules_node//node:defs.bzl', 'npm_library')

npm_library(
    name = 'jsdom-global',
    npm_req = 'jsdom-global@3.0.2',
    shrinkwrap = 'npm-shrinkwrap.json',
    contents = [
        'jsdom-global/.npmignore',
        'jsdom-global/.travis.yml',
        'jsdom-global/HISTORY.md',
        'jsdom-global/README.md',
        'jsdom-global/browser.js',
        'jsdom-global/index.js',
        'jsdom-global/keys.js',
        'jsdom-global/package.json',
        'jsdom-global/register.js',
        'jsdom-global/test.js',
    ],
)